services:
    app:
        build:
            context: ./build
            dockerfile: Dockerfile-php-dev-$APP_HOST_CPU
            args:
                APP_USER_ID: $APP_USER_ID
                APP_GROUP_ID: $APP_GROUP_ID
        image: optimus-prime-$APP_HOST_CPU-php
        container_name: optimus-prime-app
        hostname: optimus-prime-app
        working_dir: /app
        command: /usr/bin/bash
        tty: true
        volumes:
            - ./:/app
